# Generated by Django 3.2.13 on 2022-05-01 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('raca', models.CharField(max_length=20)),
                ('idade', models.IntegerField()),
            ],
        ),
    ]
